class_name DemonHierarchy
extends RefCounted

## K4.3/K4.5. A read-only classifier over subjects that already exist —
## never a demon generator. `DESIGN/COSMOLOGY.md`'s four tiers (Leadership /
## Princes / Captains / Lesser demons) are not four systems; they are one
## reading applied to subjects `RivalRegistry` (F4.1), `bone_yard_hunt.gd`'s
## seed and `cosmology_factions.gd` already produce. K4.3 in particular:
## "Lesser demons roaming, generated by F4.1 rather than authored" — this
## file authors no lesser demon. It only says which already-generated rivals
## qualify as one.

const TIER_LEADERSHIP := "LEADERSHIP"
const TIER_SIN := "SIN"
const TIER_CAPTAIN := "CAPTAIN"
const TIER_LESSER_DEMON := "LESSER DEMON"

## The seven Sin-factions, four seeded in `bone_yard_hunt.gd` and three in
## `cosmology_factions.gd`. Kept here rather than imported so this file has no
## load-order dependency on either.
const SIN_FACTIONS := ["ashline_wreckers", "black_mile", "soft_rot", "choir_of_marrow", "vanity_row", "honeyvein", "long_static"]
const LEADERSHIP_FACTION := "celloutz"


## The tier a subject reads as right now, or "" if it is not part of this
## hierarchy at all (an ascending subject, an unaffiliated bystander, ...).
static func tier(subject_id: String) -> String:
	var subject := WorldHistory.subject(subject_id)
	if subject.is_empty():
		return ""
	var kind := str(subject.get("kind", ""))
	if kind == "faction":
		if subject_id == LEADERSHIP_FACTION:
			return TIER_LEADERSHIP
		if SIN_FACTIONS.has(subject_id):
			return TIER_SIN
		return ""
	if kind != "person":
		return ""
	# K2.2. A person actually holding CellOutz's CROWN rank is a Horseman —
	# whoever WireNet.promote_successor() puts there. Dead does not clear a
	# fallen holder's own faction_rank field (nothing downstream needed it
	# to), so a corpse still reading "CROWN" on paper does not still count.
	if str(subject.get("faction_id", "")) == LEADERSHIP_FACTION and str(subject.get("faction_rank", "")) == "CROWN" and not WireNet.DEAD_STATUSES.has(str(subject.get("status", "")).to_lower()):
		return TIER_LEADERSHIP
	var faction_id := str(subject.get("faction_id", ""))
	if SIN_FACTIONS.has(faction_id) and _commands_own_faction(subject_id, faction_id):
		return TIER_CAPTAIN
	if bool(subject.get("is_rival", false)) and faction_id.is_empty():
		return TIER_LESSER_DEMON
	return ""


static func is_lesser_demon(subject_id: String) -> bool:
	return tier(subject_id) == TIER_LESSER_DEMON


## A faction's own `relations` already say who commands it (the same edge
## `WireNet.pyramid()` sorts on) — reused rather than re-deciding rank from a
## second field, so seeded captains like the captain read correctly without
## needing an explicit `faction_rank` nobody wrote for them.
static func _commands_own_faction(subject_id: String, faction_id: String) -> bool:
	var relations: Dictionary = WorldHistory.subject(faction_id).get("relations", {})
	var edge: Dictionary = relations.get(subject_id, {})
	return str(edge.get("kind", "")) == "command"


## Every currently-roaming lesser demon: any rival F4.1 produced who was never
## folded into a Sin's roster. Read fresh each call rather than cached, since
## RivalRegistry can promote a subject to `is_rival` at any point in the run.
static func lesser_demons() -> Array[String]:
	var out: Array[String] = []
	for subject_id in WorldHistory.all_subjects():
		if is_lesser_demon(subject_id):
			out.append(subject_id)
	return out
