#!/bin/bash
# The thing you read when you get back. One file, current as of the last tick.
set -u
R=/c/Users/Greg/lane-runner
P=/p/GameDev/AllusionsTooGrandeur
OUT=$R/STATUS.md
cd "$P" || exit 1
NOW=$(date +%s)
{
echo "# Status — $(date '+%A %d %B, %H:%M')"
echo
echo "Generated by \`report.sh\`. Regenerates every 30 minutes."
echo
echo "## Landed on trunk since the automation started"
echo
n=$(git rev-list --count 7e59b33..HEAD 2>/dev/null)
if [ "${n:-0}" -eq 0 ]; then echo "_Nothing yet._"; else git log --oneline 7e59b33..HEAD | sed 's/^/- /'; fi
echo
echo "## Lanes"
echo
while IFS=$'\t' read -r lane wt note; do
  if [ -f "$R/state/$wt.running" ]; then s="**running**"; else s="idle"; fi
  c=$(git rev-list --count codex/game-planning..$wt 2>/dev/null)
  echo "- \`$wt\` — $s, ${c:-0} commit(s) waiting to merge"
done < "$R/lanes.tsv"
echo
echo "## Accounts"
echo
while IFS=$'\t' read -r kind id label; do
  if [ -f "$R/state/$id.running" ]; then
    echo "- $kind \`$label\` — **in use**"
  elif [ -f "$R/state/$id.blocked" ]; then
    u=$(cat "$R/state/$id.blocked"); why=$(cat "$R/state/$id.reason" 2>/dev/null)
    if [ "$NOW" -ge "$u" ]; then echo "- $kind \`$label\` — **free now** (block expired)"
    else echo "- $kind \`$label\` — blocked until $(date -d @$u '+%a %d %b %H:%M' 2>/dev/null) · $why"; fi
  else
    echo "- $kind \`$label\` — **free**"
  fi
done < "$R/accounts.tsv"
echo
echo "## Branches still carrying unmerged work"
echo
for b in $(git for-each-ref --format='%(refname:short)' refs/heads | grep -v '^codex/game-planning$'); do
  c=$(git rev-list --count codex/game-planning..$b 2>/dev/null)
  [ "${c:-0}" -gt 0 ] || continue
  if git merge-tree --write-tree --name-only codex/game-planning "$b" >/dev/null 2>&1; then v="merges clean"; else v="**conflicts — needs you**"; fi
  echo "- \`$b\` — $c commit(s), $v"
done
echo
echo "## Test signal"
echo
if [ -f "$R/sweep.log" ]; then
  if grep -q SWEEP_DONE "$R/sweep.log"; then st="complete"; else st="still running ($(grep -c '^ok\|^SILENT\|^FAILING' "$R/sweep.log") of 252)"; fi
  echo "Sweep $st. Silent: **$(grep -c '^SILENT' "$R/sweep.log")**. Failing: **$(grep -c '^FAILING' "$R/sweep.log")**. Clean: $(grep -c '^ok' "$R/sweep.log")."
  echo
  grep '^SILENT\|^FAILING' "$R/sweep.log" | head -25 | sed 's/^/- /'
else
  echo "_No sweep has run._"
fi
echo
echo "## Decisions waiting on you"
echo
grep -E '^### [0-9]\.' "$P/MERGE_STATUS.md" 2>/dev/null | sed 's/^### /- /'
echo
echo "Full detail in \`MERGE_STATUS.md\`. Automation described in \`setup/ORCA_AUTOMATION.md\`."
} > "$OUT"
